import { boxSprinkles } from '@layout/box/Box.css.ts'
import { FlexStyleProps } from '@layout/flex/Flex.css.ts'
import { Children, element, ElementType } from '@rvjs/core/dom'
import { mergeClass } from '@util/class.js'
import { Properties } from 'csstype'

interface FlexProps extends FlexStyleProps {
  as?: ElementType
  children?: Children
  className?: string
  style?: Partial<Properties>
}

const Flex = (props: FlexProps) => {
  const {
    as = 'div',
    children = [],
    className = '',
    style = {},
    position,
    top,
    bottom,
    right,
    left,
    padding,
    paddingTop,
    paddingBottom,
    paddingLeft,
    paddingRight,
    margin,
    marginTop,
    marginBottom,
    marginLeft,
    marginRight,
    zIndex,
    alignItems,
    justifyContent,
    flexDirection,
    flexWrap,
    flexGrow,
    flexShrink,
    gap,
    color,
    backgroundColor,
    opacity,
    overflow,
    m,
    mt,
    mr,
    me,
    mb,
    ml,
    ms,
    marginX,
    marginY,
    mx,
    my,
    p,
    pt,
    pr,
    pe,
    pb,
    pl,
    ps,
    paddingX,
    paddingY,
    px,
    py,
    bgColor,
    align,
    justify,
    wrap,
    direction,
  } = props

  return element(as, {
    className: mergeClass([
      boxSprinkles({
        display: 'flex',
        position,
        top,
        bottom,
        right,
        left,
        padding,
        paddingTop,
        paddingBottom,
        paddingLeft,
        paddingRight,
        margin,
        marginTop,
        marginBottom,
        marginLeft,
        marginRight,
        zIndex,
        alignItems: align || alignItems,
        justifyContent: justify || justifyContent,
        flexDirection: direction || flexDirection,
        flexWrap: wrap || flexWrap,
        flexGrow,
        flexShrink,
        gap,
        color,
        backgroundColor,
        opacity,
        overflow,
        m,
        mt,
        mr,
        me,
        mb,
        ml,
        ms,
        marginX,
        marginY,
        mx,
        my,
        p,
        pt,
        pr,
        pe,
        pb,
        pl,
        ps,
        paddingX,
        paddingY,
        px,
        py,
        bgColor,
      }),
      className,
    ]),
    children,
    style,
  })
}

export default Flex
