import vars from '@theme/variable/vars.css.ts'
import { createSprinkles, defineProperties } from '@vanilla-extract/sprinkles'

export type BoxStyleProps = Parameters<typeof boxSprinkles>[0]

export const boxDefineProps = defineProperties({
  properties: {
    display: ['none', 'block', 'inline', 'inline-block', 'flex', 'grid'],
    position: ['absolute', 'relative', 'fixed', 'sticky'],
    top: vars.spacing,
    bottom: vars.spacing,
    right: vars.spacing,
    left: vars.spacing,
    padding: vars.spacing,
    paddingX: vars.spacing,
    paddingY: vars.spacing,
    paddingTop: vars.spacing,
    paddingBottom: vars.spacing,
    paddingLeft: vars.spacing,
    paddingRight: vars.spacing,
    paddingInlineStart: vars.spacing,
    paddingInlineEnd: vars.spacing,
    margin: vars.spacing,
    marginX: vars.spacing,
    marginY: vars.spacing,
    marginTop: vars.spacing,
    marginBottom: vars.spacing,
    marginLeft: vars.spacing,
    marginRight: vars.spacing,
    marginInlineStart: vars.spacing,
    marginInlineEnd: vars.spacing,
    zIndex: [-1, 0, 1],
    alignItems: [
      'center',
      'start',
      'end',
      'flex-start',
      'flex-end',
      'self-start',
      'self-end',
    ],
    justifyContent: [
      'start',
      'flex-start',
      'center',
      'end',
      'flex-end',
      'space-around',
      'space-between',
      'space-evenly',
    ],
    flexDirection: ['row', 'column', 'row-reverse', 'column-reverse'],
    flexWrap: ['wrap', 'nowrap'],
    flexGrow: [0, 1],
    flexShrink: [0, 1],
    gap: vars.spacing,
    color: vars.color,
    backgroundColor: vars.color,
    opacity: vars.opacity,
    overflow: ['hidden', 'auto', 'scroll', 'visible'],
  },
  shorthands: {
    m: ['margin'],
    mt: ['marginTop'],
    mr: ['marginRight'],
    me: ['marginInlineEnd'],
    mb: ['marginBottom'],
    ml: ['marginLeft'],
    ms: ['marginInlineStart'],
    marginX: ['marginLeft', 'marginRight'],
    marginY: ['marginTop', 'marginBottom'],
    mx: ['marginLeft', 'marginRight'],
    my: ['marginTop', 'marginBottom'],
    p: ['padding'],
    pt: ['paddingTop'],
    pr: ['paddingRight'],
    pe: ['paddingInlineEnd'],
    pb: ['paddingBottom'],
    pl: ['paddingLeft'],
    ps: ['paddingInlineStart'],
    paddingX: ['paddingLeft', 'paddingRight'],
    paddingY: ['paddingTop', 'paddingBottom'],
    px: ['paddingLeft', 'paddingRight'],
    py: ['paddingTop', 'paddingBottom'],
    bgColor: ['backgroundColor'],
  },
})

export const boxSprinkles = createSprinkles(boxDefineProps)
