import { boxSprinkles, BoxStyleProps } from '@layout/box/Box.css.ts'
import {
  Children,
  dynamic,
  element,
  ElementType,
  Prop,
  RefObject,
  StyleProps,
} from '@rvjs/core'
import { HTMLDivType } from '@type/element.ts'

interface BoxProps extends BoxStyleProps, HTMLDivType {
  as?: ElementType
  children?: Children
  classes?: (Prop<string> | Prop<string[]>)[]
  style?: Partial<StyleProps>
  ref?: RefObject<HTMLDivElement>
}

const Box = (props: BoxProps) => {
  const {
    as = 'div',
    children = [],
    classes = [],
    style = {},
    ref,
    display,
    position,
    top,
    bottom,
    right,
    left,
    padding,
    paddingTop,
    paddingBottom,
    paddingLeft,
    paddingRight,
    margin,
    marginTop,
    marginBottom,
    marginLeft,
    marginRight,
    zIndex,
    alignItems,
    justifyContent,
    flexDirection,
    flexWrap,
    flexGrow,
    flexShrink,
    gap,
    color,
    backgroundColor,
    opacity,
    overflow,
    m,
    mt,
    mr,
    me,
    mb,
    ml,
    ms,
    marginX,
    marginY,
    mx,
    my,
    p,
    pt,
    pr,
    pe,
    pb,
    pl,
    ps,
    paddingX,
    paddingY,
    px,
    py,
    bgColor,
    ...restProps
  } = props
  const restPropsObject: any = restProps

  return element(as, {
    ref,
    classes: [
      boxSprinkles({
        display: 'block',
        position,
        top,
        bottom,
        right,
        left,
        padding,
        paddingTop,
        paddingBottom,
        paddingLeft,
        paddingRight,
        margin,
        marginTop,
        marginBottom,
        marginLeft,
        marginRight,
        zIndex,
        alignItems,
        justifyContent,
        flexDirection,
        flexWrap,
        flexGrow,
        flexShrink,
        gap,
        color,
        backgroundColor,
        opacity,
        overflow,
        m,
        mt,
        mr,
        me,
        mb,
        ml,
        ms,
        marginX,
        marginY,
        mx,
        my,
        p,
        pt,
        pr,
        pe,
        pb,
        pl,
        ps,
        paddingX,
        paddingY,
        px,
        py,
        bgColor,
      }).split(' '),
      ...classes.map((cls) => dynamic(() => cls())),
    ],
    children,
    style,
    ...restPropsObject,
  })
}

export default Box
