export const RVJS_GET_STATE_IDENTIFIER = Symbol.for('RVJS_GET_STATE_IDENTIFIER')

export const RVJS_SET_STATE_IDENTIFIER = Symbol.for('RVJS_SET_STATE_IDENTIFIER')

export const RVJS_COMPONENT_IDENTIFIER = Symbol.for('RVJS_COMPONENT_IDENTIFIER')

export const RVJS_BLOCK_COMPONENT_IDENTIFIER = Symbol.for(
  'RVJS_BLOCK_COMPONENT_IDENTIFIER',
)

export const RVJS_FOR_COMPONENT_IDENTIFIER = Symbol.for(
  'RVJS_FOR_COMPONENT_IDENTIFIER',
)

export const RVJS_SWITCH_COMPONENT_IDENTIFIER = Symbol.for(
  'RVJS_SWITCH_COMPONENT_IDENTIFIER',
)

export const RVJS_CASE_COMPONENT_IDENTIFIER = Symbol.for(
  'RVJS_CASE_COMPONENT_IDENTIFIER',
)

export const RVJS_TOGGLE_COMPONENT_IDENTIFIER = Symbol.for(
  'RVJS_TOGGLE_COMPONENT_IDENTIFIER',
)

export const RVJS_REFRESH_COMPONENT_IDENTIFIER = Symbol.for(
  'RVJS_REFRESH_COMPONENT_IDENTIFIER',
)

export const RVJS_COMPONENT_FN_IDENTIFIER = Symbol.for(
  'RVJS_COMPONENT_FN_IDENTIFIER',
)
